use_frameworks!

platform :ios, '10.0'

target 'DesuCircularButton_Example' do
  pod 'DesuCircularButton', :path => '../'

  target 'DesuCircularButton_Tests' do
    inherit! :search_paths

    
  end
end
